[versions]
androidGradlePlugin = "8.11.0"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"

jetbrainsCompose = "1.9.0-alpha02"

kotlinPoet = "2.2.0"
kotlinxSerialization = "1.8.1"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxDatetime = "0.6.2"

androidxActivityCompose = "1.12.0-alpha03"
androidxNavigation3 = "1.0.0-alpha04"
androidxNavigation3Material = "1.0.0-SNAPSHOT"
androidxDatastore = "1.1.7"
androidxAppCompat = "1.7.1"
androidxTestCore = "1.6.1"

ktor = "3.1.3"
ktorfit = "2.5.2"

soil = "1.0.0-alpha10"

rin = "0.3.0"

metro = "0.3.8"
mokkery = "2.8.0"

lifecycleCompose = "2.9.1"
lifecycleViewmodelNavigation3 = "1.0.0-SNAPSHOT"

robolectric = "4.15.1"

composeBom = "2025.06.01"
roborazzi = "1.45.1"

detekt = "1.23.8"
twitterComposeRule = "0.0.26"
navigationeventDesktop = "1.0.0-alpha03"

composeHotReload = "1.0.0-beta03"

[libraries]
# gradle plugins
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kspGradlePlugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
jetbrainsComposeGradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrainsCompose" }
kotlinxSerializationGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidGradlePlugin" }
composeCompilerGradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
metroGradlePlugin = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
mokkeryGradlePlugin = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

# ktor and ktorfit
ktorClientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorKotlinxSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorfitLib = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }

# androidx
androidxDatastorePreferencesCore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDatastore" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidxAppCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidxTestCore = { module = "androidx.test:core", version.ref = "androidxTestCore" }


composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidxUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidxUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }

# kotlin
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# kotlinx
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxCollectionsImmutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# soil
soilQueryCore = { module = "com.soil-kt.soil:query-core", version.ref = "soil" }
soilQueryCompose = { module = "com.soil-kt.soil:query-compose", version.ref = "soil" }
soilReacty = { module = "com.soil-kt.soil:reacty", version.ref = "soil" }

# compiler
kspSymbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinPoetKsp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }

rin = { module = "io.github.takahirom.rin:rin", version.ref = "rin" }

# navigation3
navigation3Ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidxNavigation3" }
navigation3Runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidxNavigation3" }
navigation3Adaptive = { module = "androidx.compose.material3.adaptive:adaptive-navigation3", version.ref = "androidxNavigation3Material" }

lifecycleViewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }
lifecycleRuntimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleCompose" }
lifecycleViewmodelNavigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNavigation3" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
twitterComposeRule = { module = "com.twitter.compose.rules:detekt", version.ref = "twitterComposeRule" }
navigationeventDesktop = { group = "androidx.navigationevent", name = "navigationevent-desktop", version.ref = "navigationeventDesktop" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }

[bundles]
plugins = [
    "kotlinGradlePlugin",
    "jetbrainsComposeGradlePlugin",
    "kotlinxSerializationGradlePlugin",
    "androidKotlinMultiplatformLibrary",
    "kspGradlePlugin",
    "composeCompilerGradlePlugin",
    "androidGradlePlugin",
    "metroGradlePlugin",
    "mokkeryGradlePlugin",
    "detektGradlePlugin",
]
