name: Assign author to PR
on:
  pull_request:
    types:
      - opened

jobs:
  assign-pr:
    # skip already assigned PRs
    if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: gh pr edit $PR_NUMBER --add-assignee $PR_AUTHOR
        # Assignment may fail for external contributors or due to permission issues.
        # We want the workflow to continue even if assignment fails.
        continue-on-error: true
