name: Spotless Check

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
      - '.github/workflows/spotless.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for clone
  pull-requests: write

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - uses: ./.github/actions/setup-java

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck

      - name: Post Comment on Failure
        if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          header: Spotless Check Failed ðŸš¨
          message: |
            Spotless check failed. Run the following command to fix it:
            ```
            ./gradlew spotlessApply
            ```
            Commit the changes to update this pull request.
